BEGIN;

CREATE TABLE IF NOT EXISTS saas.activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NULL REFERENCES saas.tenants(id) ON DELETE CASCADE,
  user_id bigint NULL REFERENCES saas.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NULL,
  entity_id bigint NULL,
  payload jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_log_tenant_created_at
  ON saas.activity_log (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_log_user_created_at
  ON saas.activity_log (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_log_action
  ON saas.activity_log (action);

COMMIT;