BEGIN;

CREATE TABLE IF NOT EXISTS core.item_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES saas.tenants(id),
  item_id bigint NOT NULL REFERENCES core.items(id),
  receipt_id bigint NULL REFERENCES core.receipts(id) ON DELETE SET NULL,
  batch_date date NOT NULL,
  qty_total numeric(14,3) NOT NULL CHECK (qty_total > 0),
  qty_remaining numeric(14,3) NOT NULL CHECK (qty_remaining >= 0),
  unit_cost numeric(14,2) NOT NULL CHECK (unit_cost >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_item_batches_tenant_item_batchdate
  ON core.item_batches (tenant_id, item_id, batch_date, id);

CREATE INDEX IF NOT EXISTS idx_item_batches_remaining
  ON core.item_batches (tenant_id, item_id, batch_date, id)
  WHERE qty_remaining > 0;

COMMIT;